import operator

from pydantic import BaseModel, Field
from typing import List, Annotated
from typing_extensions import TypedDict
from langgraph.graph.message import AnyMessage, add_messages
from langgraph.graph import MessagesState


class Email(BaseModel):
    id: str = Field(..., description="Unique identifier of the email")
    sender: str = Field(..., description="Email address of the sender")
    name: str = Field(..., description="Name of the email address")
    subject: str = Field(..., description="Subject line of the email")
    body: str = Field(..., description="Body content of the email")

def reducer(a,b):
    return b
class GraphState(TypedDict):
    """
    Represents the state of the email processing graph.

    Attributes:
        emails (List[Email]): List of Email objects containing details of new emails.
        current_email (Email): The Email object currently being processed.
        current_email_name (Email): Name of the email address
        email_category (str): Category of the current email (e.g., product enquiry, customer feedback).
        generated_email (str): Content of the email generated by the write agent.
        rag_questions (List[str]): List of questions designed for Retrieval-Augmented Generation (RAG).
        retrieved_documents (str): Documents retrieved from RAG to answer enquiry.
        review (str): Review result of the generated email (send or rewrite).
        trials (int): Number of draft trials attempted before stopping.
        lead_info(dict): Information about the lead
    """

    emails: Annotated[List[Email],reducer]
    current_email: Annotated[Email, reducer]
    current_email_name: Annotated[Email,reducer]
    email_category: Annotated[str,reducer]
    generated_email: Annotated[str,reducer]
    rag_questions: Annotated[List[str],reducer]
    retrieved_documents: Annotated[str,reducer]
    review: Annotated[str,reducer]
    trials: Annotated[str,reducer]
    lead_name: Annotated[str,reducer]
    lead_info: Annotated[str,reducer]
    lead_mail: Annotated[Email,reducer]
    company_name: Annotated[str,reducer]
    lead_info_summary: Annotated[str,reducer]
    welcome_email: Annotated[Email,reducer]
    welcome_trails: Annotated[str,reducer]
    welcome_email_review: Annotated[str,reducer]
    owner_id: Annotated[str,reducer]
    record_id: Annotated[str,reducer]
    call_subject:Annotated[str,reducer]
    call_purpose:Annotated[str,reducer]
    call_date_time:Annotated[str,reducer]
    call_description:Annotated[str,reducer]
    call_scheduled:Annotated[str,reducer]
    lead_status:Annotated[str,reducer] # ["Qualified", "Not Qualified"]
    lead_qualified:Annotated[str,reducer]
    email_sentiment:Annotated[str,reducer]
    email_intent:Annotated[str,reducer]
    email_interest:Annotated[str,reducer]
    email_emotion:Annotated[str,reducer]
    contact_converted:Annotated[str,reducer]
    lead_type:Annotated[str,reducer] # ["new","old"]
    contact_created:Annotated[str,reducer]
    messages: Annotated[list[AnyMessage], add_messages]
